#!/usr/bin/env bash
# Emits: hostname --- nixos-version --- uptime --- last-profile-activation --- user-face-icon --- is-nixos
cat /etc/hostname 2>/dev/null || hostname 2>/dev/null
echo '---'
cat /run/current-system/nixos-version 2>/dev/null
echo '---'
awk '{s=$1; h=int(s/3600); m=int((s%3600)/60); printf "%dh %dm", h, m}' /proc/uptime 2>/dev/null
echo '---'
stat --format='%y' /nix/var/nix/profiles/system 2>/dev/null | cut -d'.' -f1
echo '---'
for f in "$HOME/.face" "$HOME/.face.icon" "/var/lib/AccountsService/icons/$USER"; do
    if [ -s "$f" ]; then
        printf '%s' "$f"
        break
    fi
done
# Last field: 1 on NixOS, 0 on any other distribution that has Nix installed.
echo
echo '---'
if [ -e /etc/NIXOS ] || grep -Eqs "^ID=(nixos|\"nixos\"|'nixos')[[:space:]]*$" /etc/os-release 2>/dev/null; then
    echo 1
else
    echo 0
fi
exit 0
